server:
  port: 1182
spring:
  application:
    name: boca-client-producer
  #链路追踪的配置
  sleuth:
    sampler: #应该采样的请求的概率，配置spans导出的概率。概率(默认值:0.1，即10%)
      probability: 1
  zipkin: #Zipkin服务器
    base-url: http://39.106.33.10:8088/
    service: #定制服务名称
      name: sleuth-producer
    sender: #把span发送到zipkin方式
      type: web
   #监控,由于admin-service注册到eureka,则admin-client不需要配置
#  boot:
#    admin:
#      client:
#        username: admin
#        password: admin
#        url: http://127.0.0.1:1121

management:
  endpoints:
    web:
      exposure:
        include: "*"  #启用所有的监控端点
  endpoint:
    health:
      show-details: ALWAYS #一直显示详细的健康信息

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/,http://localhost:1112/eureka/,http://localhost:1113/eureka/