server:
  port: 1170
spring:
  application:
    name: boca-mq-stream-provider
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitMQ的服务信息
        defaultRabbit: # 表示定义的名称，用于binding的整合
          type: rabbit # 消息中间件类型
          environment: # 设置rabbitMQ的相关环境配置
            spring:
              rabbitmq:
                host: 39.106.33.10
                port: 5672
                username: quboka
                password: quboka
        qbkRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 39.106.33.10
                port: 5672
                username: quboka
                password: quboka
      bindings: # 服务的整合处理
        output: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设为text/plain
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
        qbkOutput:
          destination: kkExchange
          content-type: application/json
          binder: qbkRabbit
eureka:
  instance:
    prefer-ip-address: true #显示ip
    lease-renewal-interval-in-seconds: 2 # 设置心跳的间隔时间，默认30
    lease-expiration-duration-in-seconds: 5 # 超过5秒间隔，默认90
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/,http://localhost:1112/eureka/,http://localhost:1113/eureka/